import type { FileManifest } from '../files/types.js';
import type { RpcHeaders } from '../rpc/headers.js';
import { containsUnsafeDisplayCharacters } from '../text.js';

export interface SessionCredential {
  /** Credential scheme understood by the configured authenticator. */
  readonly scheme: string;
  /** Secret credential material. It is sent only inside the encrypted session handshake. */
  readonly value: string;
}

export interface SessionPrincipal {
  /** Stable local identifier for authorization and audit records. */
  readonly id: string;
  /** OAuth/OIDC subject, service-account ID, or equivalent identity. */
  readonly subject: string;
  readonly issuer?: string;
  /** Verified OAuth client_id/azp identifying the authorized calling application. */
  readonly clientId?: string;
  readonly tenantId?: string;
  /** Absolute Unix time in milliseconds after which the session must stop accepting work. */
  readonly expiresAt: number;
  readonly scopes: ReadonlySet<string>;
  /** Verified claims. Never place unverified request metadata in this object. */
  readonly claims: Readonly<Record<string, unknown>>;
}

export interface CredentialRequestContext {
  readonly localPeerId: string;
  readonly remotePeerId: string;
  readonly direction: 'inbound' | 'outbound';
  readonly protocol: string;
  /** The nonce generated by the side presenting this credential. */
  readonly nonce: string;
  /** Aborted when the handshake times out or otherwise terminates. */
  readonly signal: AbortSignal;
}

export interface SessionAuthenticationContext {
  readonly localPeerId: string;
  readonly remotePeerId: string;
  readonly direction: 'inbound' | 'outbound';
  readonly protocol: string;
  readonly initiatorPeerId: string;
  readonly responderPeerId: string;
  readonly initiatorNonce: string;
  readonly responderNonce: string;
  readonly presentedAt: number;
  /** Aborted when the handshake times out or otherwise terminates. */
  readonly signal: AbortSignal;
}

export type AuthorizationAction<TFileMetadata = unknown> =
  | {
      readonly kind: 'rpc';
      readonly path: string;
      readonly type: 'query' | 'mutation' | 'subscription';
      /** Untrusted, bounded application metadata supplied by the caller. */
      readonly headers: RpcHeaders;
    }
  | {
      readonly kind: 'file.push';
      readonly manifest: FileManifest<TFileMetadata>;
    }
  | {
      readonly kind: 'file.pull';
      /** A non-secret hash of the presented capability, suitable for audit correlation. */
      readonly capabilityId: string;
    };

export interface AuthorizationContext<TFileMetadata = unknown> {
  readonly principal: SessionPrincipal;
  readonly localPeerId: string;
  readonly remotePeerId: string;
  readonly sessionId: string;
  readonly action: AuthorizationAction<TFileMetadata>;
  /** Aborted when the authorization deadline, request, or session terminates. */
  readonly signal: AbortSignal;
}

export type AuthorizationResult = boolean | { readonly allowed: boolean; readonly reason?: string };

/**
 * Application authentication and authorization for an encrypted Iroh session.
 *
 * Implementations commonly verify short-lived OAuth access tokens, but may use
 * workload identities, mTLS-derived assertions, or an enterprise introspection
 * service. Transport peer IDs are passed into every check so credentials can be
 * proof-of-possession bound to the exact Iroh endpoint key.
 */
export interface SessionSecurity<TFileMetadata = unknown> {
  getCredential(context: CredentialRequestContext): Promise<SessionCredential> | SessionCredential;
  authenticate(
    credential: SessionCredential,
    context: SessionAuthenticationContext
  ): Promise<SessionPrincipal> | SessionPrincipal;
  authorize(context: AuthorizationContext<TFileMetadata>): Promise<AuthorizationResult> | AuthorizationResult;
}

export interface AuthenticatedSession {
  readonly id: string;
  readonly establishedAt: number;
  readonly expiresAt: number;
  readonly principal: SessionPrincipal;
}

export function authorizationAllowed(result: AuthorizationResult): { allowed: boolean; reason?: string } {
  if (typeof result === 'boolean') return { allowed: result };
  if (!result || typeof result !== 'object' || typeof result.allowed !== 'boolean') {
    throw new TypeError('Security authorizer returned an invalid decision');
  }
  if (result.reason !== undefined && typeof result.reason !== 'string') {
    throw new TypeError('Security authorizer returned an invalid reason');
  }
  return result.reason === undefined ? { allowed: result.allowed } : { allowed: result.allowed, reason: result.reason };
}

export function freezePrincipal(principal: SessionPrincipal): SessionPrincipal {
  if (!principal || typeof principal !== 'object') throw new TypeError('Authenticator returned an invalid principal');
  if (!validIdentityField(principal.id, 2048) || !validIdentityField(principal.subject, 2048)) {
    throw new TypeError('Authenticated principal must have bounded id and subject strings');
  }
  if (principal.issuer !== undefined && !validIdentityField(principal.issuer, 4096)) {
    throw new TypeError('Authenticated principal has an invalid issuer');
  }
  if (principal.clientId !== undefined && !validIdentityField(principal.clientId, 2048)) {
    throw new TypeError('Authenticated principal has an invalid OAuth client ID');
  }
  if (principal.tenantId !== undefined && !validIdentityField(principal.tenantId, 2048)) {
    throw new TypeError('Authenticated principal has an invalid tenant ID');
  }
  if (!Number.isSafeInteger(principal.expiresAt)) throw new TypeError('Authenticated principal must have an integer expiresAt');
  if (!principal.claims || typeof principal.claims !== 'object' || Array.isArray(principal.claims)) {
    throw new TypeError('Authenticated principal claims must be a record');
  }
  const scopeValues = [...principal.scopes];
  if (scopeValues.length > 1024 || scopeValues.some((scope) => !validIdentityField(scope, 1024))) {
    throw new TypeError('Authenticated principal has invalid scopes');
  }
  const claims = freezeClaims(principal.claims, 0) as Readonly<Record<string, unknown>>;
  const scopes = immutableSet(scopeValues);
  return Object.freeze({
    id: principal.id,
    subject: principal.subject,
    ...(principal.issuer !== undefined ? { issuer: principal.issuer } : {}),
    ...(principal.clientId !== undefined ? { clientId: principal.clientId } : {}),
    ...(principal.tenantId !== undefined ? { tenantId: principal.tenantId } : {}),
    expiresAt: principal.expiresAt,
    scopes,
    claims
  });
}

function validIdentityField(value: unknown, maximumBytes: number): value is string {
  return typeof value === 'string' &&
    value.length > 0 &&
    Buffer.byteLength(value) <= maximumBytes &&
    !containsUnsafeDisplayCharacters(value);
}

function immutableSet<T>(values: Iterable<T>): ReadonlySet<T> {
  const inner = new Set(values);
  const view: ReadonlySet<T> = {
    get size() { return inner.size; },
    has: (value) => inner.has(value),
    entries: () => inner.entries(),
    keys: () => inner.keys(),
    values: () => inner.values(),
    forEach(callback, thisArg) {
      inner.forEach((value) => callback.call(thisArg, value, value, view));
    },
    [Symbol.iterator]: () => inner[Symbol.iterator]()
  };
  return Object.freeze(view);
}

function freezeClaims(value: unknown, depth: number): unknown {
  if (depth > 32) throw new TypeError('Authenticated claims exceed the maximum nesting depth');
  if (Array.isArray(value)) return Object.freeze(value.map((item) => freezeClaims(item, depth + 1)));
  if (value && typeof value === 'object') {
    const copy: Record<string, unknown> = Object.create(null) as Record<string, unknown>;
    for (const [key, item] of Object.entries(value)) copy[key] = freezeClaims(item, depth + 1);
    return Object.freeze(copy);
  }
  return value;
}
