import { randomBytes } from 'node:crypto';
import { setTimeout as delay } from 'node:timers/promises';
import { initTRPC } from '@trpc/server';
import { afterEach, describe, expect, it } from 'vitest';
import { z } from 'zod';
import { P2PError } from '../src/errors.js';
import { createSharedSecretSecurity, type ConnectOptions, type Peer, type PeerContext } from '../src/index.js';
import { createAdvancedP2PNode, type P2PNodeLimits, type SecurityAuditEvent } from '../src/node.js';
import type { SessionSecurity } from '../src/security/types.js';
import { PROTOCOL_VERSION, SessionFrameKind, StreamKind, writeFrame, writeStreamKind } from '../src/protocol.js';
import type { QuicConnection } from '../src/transport/types.js';

const t = initTRPC.context<PeerContext>().create();
const ttlMs = 800;
const nodes: Array<{ close(): Promise<void> }> = [];
const cleanup: Array<() => void> = [];
afterEach(async () => {
  for (const release of cleanup.splice(0)) release();
  await Promise.all(nodes.splice(0).map((node) => node.close()));
});

function deferred<T>() {
  let resolve!: (value: T) => void;
  const promise = new Promise<T>((accept) => { resolve = accept; });
  return { promise, resolve };
}

function untilAborted(signal: AbortSignal | undefined): Promise<void> {
  if (signal?.aborted) return Promise.resolve();
  return new Promise((resolve) => signal?.addEventListener('abort', () => resolve(), { once: true }));
}

function fixture() {
  const release = deferred<void>();
  cleanup.push(() => release.resolve());
  const state = {
    busyStarts: 0,
    idleStarts: 0,
    idleEnds: 0,
    readStarts: 0,
    readAborts: 0,
    mutationStarts: 0,
    mutationAborts: 0,
    receipts: new Map<string, 'settled'>(),
    release,
    events: Array.from({ length: 80 }, (_, index) => ({ cursor: index + 1, value: `event-${index + 1}` }))
  };
  const router = t.router({
    ping: t.procedure.query(() => 'pong'),
    busy: t.procedure.input(z.number().int().min(0)).subscription(async function* ({ input, signal }) {
      state.busyStarts += 1;
      for (const event of state.events.filter((entry) => entry.cursor > input)) {
        if (signal?.aborted) return;
        yield event;
        await delay(35, undefined, { signal }).catch(() => undefined);
      }
    }),
    idle: t.procedure.subscription(async function* ({ signal }) {
      state.idleStarts += 1;
      try {
        yield 'ready';
        await Promise.race([release.promise, untilAborted(signal)]);
        if (!signal?.aborted) yield 'after-renewal';
      } finally {
        state.idleEnds += 1;
      }
    }),
    read: t.procedure.query(async ({ signal, ctx }) => {
      state.readStarts += 1;
      signal?.addEventListener('abort', () => { state.readAborts += 1; }, { once: true });
      await Promise.race([release.promise, untilAborted(signal)]);
      return { sessionId: ctx.p2p.auth.id };
    }),
    mutate: t.procedure.input(z.string()).mutation(async ({ input, signal }) => {
      state.mutationStarts += 1;
      signal?.addEventListener('abort', () => { state.mutationAborts += 1; }, { once: true });
      // Deliberately models a side effect which does not honor cancellation.
      // Recovery reads its same operation identity; transport must never replay it.
      await release.promise;
      state.receipts.set(input, 'settled');
      return input;
    }),
    receipt: t.procedure.input(z.string()).query(({ input }) => state.receipts.get(input) ?? 'pending')
  });
  return { router, state };
}

type Router = ReturnType<typeof fixture>['router'];

async function pair(
  router: Router,
  options: {
    sessionTtlMs?: number;
    serverLimits?: Partial<P2PNodeLimits>;
    clientSecurity?: (security: SessionSecurity) => SessionSecurity;
    serverSecurity?: (security: SessionSecurity) => SessionSecurity;
  } = {}
) {
  const secret = randomBytes(32);
  const events: SecurityAuditEvent[] = [];
  const inbound: Peer<Router>[] = [];
  const base = () => createSharedSecretSecurity(secret, { sessionTtlMs: options.sessionTtlMs ?? ttlMs, authorize: () => true });
  const make = async (security: SessionSecurity, onPeer?: (peer: Peer<Router>) => void, limits?: Partial<P2PNodeLimits>) => {
    const node = await createAdvancedP2PNode({
      router,
      protocol: { applicationId: 'renewal-real-transport', contractVersion: '1' },
      security,
      createContext: (context) => context,
      onSecurityEvent: (event) => events.push(event),
      ...(limits ? { limits } : {}),
      ...(onPeer ? { onPeer: (peer) => onPeer(peer as Peer<Router>) } : {}),
      iroh: {
        relayMode: 'disabled',
        bindAddress: '0.0.0.0:0',
        // Iroh advertises local interface addresses rather than loopback. Both
        // tickets in this fixture are generated by these disposable endpoints.
        allowDirectAddress: () => true
      }
    });
    nodes.push(node);
    return node;
  };
  const server = await make(options.serverSecurity?.(base()) ?? base(), (peer) => inbound.push(peer), options.serverLimits);
  const client = await make(options.clientSecurity?.(base()) ?? base());
  const target: ConnectOptions = {
    locator: { kind: 'ticket', ticket: server.ticket() },
    expectedPeerId: server.id,
    expectedPrincipal: { id: server.id, subject: server.id, issuer: null, clientId: null, tenantId: null }
  };
  return { server, client, target, events, inbound, makeClient: () => make(options.clientSecurity?.(base()) ?? base()) };
}

function physicalConnection(peer: Peer<Router>): QuicConnection {
  return (peer as unknown as { runtime: { current: QuicConnection } }).runtime.current;
}

async function waitForRenewals(peer: Peer<Router>, initialGeneration: number, count = 3) {
  await expect.poll(() => peer.session.generation, { timeout: 6_000, interval: 20 })
    .toBeGreaterThanOrEqual(initialGeneration + count);
}

describe('authenticated renewal over disposable local Iroh QUIC', () => {
  it('preserves idle/busy subscriptions, reads, mutations and connection identity through three real expiry boundaries', { timeout: 20_000 }, async () => {
    const { router, state } = fixture();
    const { client, server, target, events, inbound } = await pair(router);
    const peer = await client.connect<Router>(target);
    const initial = peer.session;
    const connection = physicalConnection(peer);
    const connectionId = (await peer.diagnostics()).connection.connectionId;
    const values: Array<{ cursor: number; value: string }> = [];
    const idleValues: string[] = [];
    const errors: unknown[] = [];
    let busyComplete = false;
    let idleComplete = false;
    const busy = peer.rpc.busy.subscribe(0, {
      onData: (value) => values.push(value),
      onError: (error) => errors.push(error),
      onComplete: () => { busyComplete = true; }
    });
    const idle = peer.rpc.idle.subscribe(undefined, {
      onData: (value) => idleValues.push(value),
      onError: (error) => errors.push(error),
      onComplete: () => { idleComplete = true; }
    });
    cleanup.push(() => { busy.unsubscribe(); idle.unsubscribe(); });
    const read = peer.rpc.read.query();
    const mutation = peer.rpc.mutate.mutate('operation-renewal');
    // Observe rejections immediately, while still asserting successful completion below.
    void read.catch(() => undefined);
    void mutation.catch(() => undefined);
    await expect.poll(() => state.mutationStarts).toBe(1);
    await waitForRenewals(peer, initial.generation);
    // Cross the wall-clock deadline of three original short security lifetimes,
    // not merely three calls to a mocked renewal method.
    await delay(Math.max(0, initial.establishedAt + 3 * ttlMs - Date.now()));
    expect(peer.session.generation).toBeGreaterThanOrEqual(3);
    expect(client.getPeer(server.id)?.session).toBe(peer.session);
    expect(physicalConnection(peer)).toBe(connection);
    expect((await peer.diagnostics()).connection.connectionId).toBe(connectionId);
    expect(inbound).toHaveLength(1);
    expect(state.busyStarts).toBe(1);
    expect(state.idleStarts).toBe(1);
    expect(state.readStarts).toBe(1);
    expect(state.mutationStarts).toBe(1);
    expect(state.readAborts).toBe(0);
    expect(state.mutationAborts).toBe(0);
    expect(idleValues).toEqual(['ready']);
    expect(idleComplete).toBe(false);
    expect(errors).toEqual([]);
    state.release.resolve();
    await expect(read).resolves.toEqual({ sessionId: initial.id });
    await expect(mutation).resolves.toBe('operation-renewal');
    await expect.poll(() => busyComplete, { timeout: 5_000 }).toBe(true);
    await expect.poll(() => idleComplete).toBe(true);
    expect(values).toEqual(state.events);
    expect(idleValues).toEqual(['ready', 'after-renewal']);
    expect(events.some((event) => event.type === 'session.expired')).toBe(false);
    const generations = events.filter((event): event is Extract<SecurityAuditEvent, { type: 'session.renewed' }> => event.type === 'session.renewed' && event.peerId === server.id);
    expect(generations.length).toBeGreaterThanOrEqual(3);
    expect(generations.map((event) => event.generation)).toEqual(generations.map((_, index) => index + 1));
  });

  it('preserves cancellation across a generation and never replays a dispatched cancelled mutation', { timeout: 15_000 }, async () => {
    const { router, state } = fixture();
    const { client, target } = await pair(router);
    const peer = await client.connect<Router>(target);
    const controller = new AbortController();
    const mutationController = new AbortController();
    const read = peer.rpc.read.query(undefined, { signal: controller.signal }).catch((error: unknown) => error);
    const mutation = peer.rpc.mutate.mutate('cancelled-operation', { signal: mutationController.signal })
      .catch((error: unknown) => error);
    const subscription = peer.rpc.idle.subscribe(undefined, { onData: () => undefined });
    cleanup.push(() => subscription.unsubscribe());
    await expect.poll(() => state.mutationStarts).toBe(1);
    await waitForRenewals(peer, peer.session.generation, 1);
    controller.abort();
    mutationController.abort();
    subscription.unsubscribe();
    await expect.poll(() => state.readAborts).toBe(1);
    await expect.poll(() => state.mutationAborts).toBe(1);
    await expect.poll(() => state.idleEnds).toBe(1);
    expect(await read).toBeInstanceOf(Error);
    expect(await mutation).toMatchObject({ cause: { code: 'OUTCOME_UNKNOWN' } });
    state.release.resolve();
    await expect.poll(() => state.receipts.get('cancelled-operation')).toBe('settled');
    await waitForRenewals(peer, peer.session.generation, 1);
    await expect(peer.rpc.receipt.query('cancelled-operation')).resolves.toBe('settled');
    expect(state.mutationStarts).toBe(1);
  });

  it('rejects invalid credentials both at initial admission and renewal without exposing credential material', { timeout: 15_000 }, async () => {
    const { router, state } = fixture();
    let invalid = true;
    const invalidValue = randomBytes(32).toString('base64url');
    const { client, server, target, events } = await pair(router, {
      clientSecurity: (security) => ({
        ...security,
        getCredential: (context) => invalid ? { scheme: 'P2PRPC-HMAC-SHA256', value: invalidValue } : security.getCredential(context)
      })
    });
    await expect(client.connect(target)).rejects.toMatchObject({ code: 'UNAUTHORIZED' });
    expect(server.getPeer(client.id)).toBeUndefined();
    invalid = false;
    const peer = await client.connect<Router>(target);
    const initialGeneration = peer.session.generation;
    let ended = false;
    const subscription = peer.rpc.idle.subscribe(undefined, {
      onData: () => undefined,
      onError: () => { ended = true; },
      onComplete: () => { ended = true; }
    });
    cleanup.push(() => subscription.unsubscribe());
    await expect.poll(() => state.idleStarts).toBe(1);
    invalid = true;
    await expect.poll(() => client.getPeer(server.id), { timeout: 3_000 }).toBeUndefined();
    await expect.poll(() => ended).toBe(true);
    expect(peer.session.generation).toBe(initialGeneration);
    expect(JSON.stringify(events)).not.toContain(invalidValue);
  });

  it('rechecks revocation policy for an idle subscription before installing replacement authentication', { timeout: 15_000 }, async () => {
    const { router, state } = fixture();
    let revoked = false;
    let authorizationChecks = 0;
    const { client, server, target } = await pair(router, {
      serverSecurity: (security) => ({
        ...security,
        authorize: () => { authorizationChecks += 1; return !revoked; }
      })
    });
    const peer = await client.connect<Router>(target);
    let ended = false;
    const subscription = peer.rpc.idle.subscribe(undefined, {
      onData: () => undefined,
      onError: () => { ended = true; },
      onComplete: () => { ended = true; }
    });
    cleanup.push(() => subscription.unsubscribe());
    await expect.poll(() => state.idleStarts).toBe(1);
    const checked = authorizationChecks;
    revoked = true;
    await expect.poll(() => ended, { timeout: 3_000 }).toBe(true);
    await expect.poll(() => server.getPeer(client.id)).toBeUndefined();
    expect(authorizationChecks).toBeGreaterThan(checked);
    expect(state.idleStarts).toBe(1);
    await expect(peer.rpc.ping.query()).rejects.toBeInstanceOf(Error);
  });

  it.each(['principal', 'scopes', 'claims'] as const)(
    'rejects a replacement whose %s would change admitted authority',
    { timeout: 15_000 },
    async (changed) => {
      const { router } = fixture();
      let replacement = false;
      const { client, server, target } = await pair(router, {
        serverSecurity: (security) => ({
          ...security,
          authenticate: async (credential, context) => {
            const principal = await security.authenticate(credential, context);
            if (!replacement) return principal;
            return {
              ...principal,
              ...(changed === 'principal' ? { subject: 'different-principal' } : {}),
              ...(changed === 'scopes' ? { scopes: new Set(['different:authority']) } : {}),
              ...(changed === 'claims' ? { claims: { ...principal.claims, tenant: 'different-tenant' } } : {})
            };
          }
        })
      });
      const peer = await client.connect<Router>(target);
      replacement = true;
      await expect.poll(() => client.getPeer(server.id), { timeout: 2_000 }).toBeUndefined();
      await expect.poll(() => server.getPeer(client.id), { timeout: 2_000 }).toBeUndefined();
      expect(peer.session.generation).toBe(0);
    }
  );

  it('bounds a replacement credential provider that never settles by the incumbent deadline', { timeout: 15_000 }, async () => {
    const { router } = fixture();
    let stall = false;
    let providerSignal: AbortSignal | undefined;
    const { client, server, target } = await pair(router, {
      clientSecurity: (security) => ({
        ...security,
        getCredential: (context) => {
          if (!stall) return security.getCredential(context);
          providerSignal = context.signal;
          return new Promise((_, reject) => {
            context.signal.addEventListener('abort', () => reject(new P2PError('CANCELLED', 'test renewal provider cancelled')), { once: true });
          });
        }
      })
    });
    const peer = await client.connect<Router>(target);
    const expiresAt = peer.session.expiresAt;
    stall = true;
    await expect.poll(() => providerSignal, { timeout: 2_000 }).toBeDefined();
    await expect.poll(() => client.getPeer(server.id), { timeout: 2_000 }).toBeUndefined();
    expect(providerSignal?.aborted).toBe(true);
    expect(Date.now()).toBeLessThan(expiresAt + 500);
    expect(peer.session.generation).toBe(0);
  });

  it.each(['duplicate-generation', 'stale-predecessor', 'clock-skew'] as const)(
    'rejects a %s renewal stream without installing another writer',
    { timeout: 15_000 },
    async (attack) => {
      const { router } = fixture();
      let credentialRequests = 0;
      const { client, server, target, events } = await pair(router, {
        serverSecurity: (security) => ({
          ...security,
          getCredential: (context) => {
            credentialRequests += 1;
            return security.getCredential(context);
          }
        })
      });
      const peer = await client.connect<Router>(target);
      const initial = peer.session;
      await waitForRenewals(peer, initial.generation, 1);
      // Enter the permitted renewal window so the transcript fence itself
      // rejects this request, rather than the early-renewal rate guard.
      await delay(ttlMs * 0.3);
      const current = peer.session;
      const requestsBeforeAttack = credentialRequests;
      const stream = await physicalConnection(peer).openBi();
      await writeStreamKind(stream.send, StreamKind.SessionAuth);
      await writeFrame(stream.send, SessionFrameKind.ClientHello, {
        version: 4,
        protocol: `p2prpc/${PROTOCOL_VERSION}/renewal-real-transport/1`,
        nonce: randomBytes(32).toString('base64url'),
        presentedAt: Date.now() - (attack === 'clock-skew' ? 60_000 : 0),
        maxSessionTtlMs: 900_000,
        generation: attack === 'duplicate-generation' ? current.generation : current.generation + 1,
        previousSessionId: attack === 'stale-predecessor' ? initial.id : current.id
      });
      await expect.poll(() => server.getPeer(client.id), { timeout: 2_000 }).toBeUndefined();
      await expect.poll(() => client.getPeer(server.id), { timeout: 2_000 }).toBeUndefined();
      expect(credentialRequests).toBe(requestsBeforeAttack);
      expect(peer.session.generation).toBe(current.generation);
      expect(events.filter((event) => event.type === 'session.renewed' && event.peerId === client.id)).toHaveLength(1);
    }
  );

  it('queues healthy renewals behind bounded verification capacity without retiring either incumbent', { timeout: 20_000 }, async () => {
    const { router, state } = fixture();
    let activeVerification = 0;
    let peakVerification = 0;
    let renewalVerifications = 0;
    const { client, server, target, events, makeClient } = await pair(router, {
      sessionTtlMs: 2_000,
      serverLimits: { maxPendingHandshakes: 1 },
      serverSecurity: (security) => ({
        ...security,
        authenticate: async (credential, context) => {
          if (context.generation === 0) return security.authenticate(credential, context);
          renewalVerifications += 1;
          activeVerification += 1;
          peakVerification = Math.max(peakVerification, activeVerification);
          try {
            await delay(250, undefined, { signal: context.signal });
            return await security.authenticate(credential, context);
          } finally {
            activeVerification -= 1;
          }
        }
      })
    });
    const secondClient = await makeClient();
    const first = await client.connect<Router>(target);
    const second = await secondClient.connect<Router>(target);
    const connections = [physicalConnection(first), physicalConnection(second)];
    const errors: unknown[] = [];
    let ended = 0;
    for (const peer of [first, second]) {
      const subscription = peer.rpc.idle.subscribe(undefined, {
        onData: () => undefined,
        onError: (error) => errors.push(error),
        onComplete: () => { ended += 1; }
      });
      cleanup.push(() => subscription.unsubscribe());
    }
    await expect.poll(() => state.idleStarts).toBe(2);
    await Promise.all([waitForRenewals(first, 0, 2), waitForRenewals(second, 0, 2)]);
    expect(server.peersSnapshot()).toHaveLength(2);
    expect(client.getPeer(server.id)).toBeDefined();
    expect(secondClient.getPeer(server.id)).toBeDefined();
    expect([physicalConnection(first), physicalConnection(second)]).toEqual(connections);
    expect(peakVerification).toBe(1);
    expect(renewalVerifications).toBeGreaterThanOrEqual(4);
    expect(state.idleStarts).toBe(2);
    expect(ended).toBe(0);
    expect(errors).toEqual([]);
    expect(events.filter((event) => event.type === 'session.rejected' || event.type === 'session.expired')).toEqual([]);
    await expect(first.rpc.ping.query()).resolves.toBe('pong');
    await expect(second.rpc.ping.query()).resolves.toBe('pong');
  });

  it('rejects cached credentials that cannot advance expiry without geometric renewal churn', { timeout: 10_000 }, async () => {
    const { router } = fixture();
    let fixedExpiry: number | undefined;
    let renewalCredentials = 0;
    const cached = (security: SessionSecurity): SessionSecurity => ({
      ...security,
      getCredential: (context) => {
        if (context.generation > 0) renewalCredentials += 1;
        return security.getCredential(context);
      },
      authenticate: async (credential, context) => {
        const principal = await security.authenticate(credential, context);
        fixedExpiry ??= Date.now() + 1_600;
        return { ...principal, expiresAt: fixedExpiry };
      }
    });
    const { client, server, target, events } = await pair(router, {
      sessionTtlMs: 1_600,
      clientSecurity: cached,
      serverSecurity: cached
    });
    const peer = await client.connect<Router>(target);
    const initial = peer.session;
    await expect.poll(() => client.getPeer(server.id), { timeout: 2_500 }).toBeUndefined();
    await expect.poll(() => server.getPeer(client.id), { timeout: 2_500 }).toBeUndefined();
    expect(peer.session).toBe(initial);
    expect(renewalCredentials).toBe(2);
    expect(events.filter((event) => event.type === 'session.renewed')).toEqual([]);
    expect(events.some((event) => event.type === 'session.rejected' && event.code === 'UNAUTHORIZED')).toBe(true);
    expect(Date.now()).toBeLessThan(initial.expiresAt);
    // Passive observation must not redial or restart another credential loop.
    await delay(Math.max(0, initial.expiresAt - Date.now()) + 100);
    expect(renewalCredentials).toBe(2);
    expect(events.filter((event) => event.type === 'session.renewed')).toEqual([]);
  });

  it('reports uncertain mutation settlement after real connection loss, recovers its receipt and resumes from the last cursor', { timeout: 15_000 }, async () => {
    const { router, state } = fixture();
    const { client, server, target, inbound } = await pair(router);
    const peer = await client.connect<Router>(target);
    const initialConnection = physicalConnection(peer);
    const values: number[] = [];
    let ended = false;
    const subscription = peer.rpc.busy.subscribe(0, {
      onData: (event) => values.push(event.cursor),
      onError: () => { ended = true; },
      onComplete: () => { ended = true; }
    });
    cleanup.push(() => subscription.unsubscribe());
    const mutation = peer.rpc.mutate.mutate('network-loss-operation').catch((error: unknown) => error);
    await expect.poll(() => state.mutationStarts).toBe(1);
    await expect.poll(() => values.length).toBeGreaterThan(3);
    initialConnection.close(1n, new TextEncoder().encode('disposable network-loss test'));
    expect(await mutation).toMatchObject({ cause: { code: 'OUTCOME_UNKNOWN' } });
    await expect.poll(() => ended).toBe(true);
    // Stream failure can precede the asynchronous physical-close observation.
    await expect.poll(() => client.getPeer(server.id)).toBeUndefined();
    await expect.poll(() => server.getPeer(client.id)).toBeUndefined();
    const lastCursor = values.at(-1)!;
    state.release.resolve();
    await expect.poll(() => state.receipts.get('network-loss-operation')).toBe('settled');
    await expect(peer.rpc.receipt.query('network-loss-operation')).resolves.toBe('settled');
    expect(physicalConnection(peer)).not.toBe(initialConnection);
    expect(state.mutationStarts).toBe(1);
    await expect.poll(() => inbound.length).toBe(2);
    await expect(inbound[0]!.rpc.ping.query()).rejects.toMatchObject({ cause: { code: 'DISCONNECTED' } });
    const resumed = deferred<void>();
    const resubscription = peer.rpc.busy.subscribe(lastCursor, {
      onData: (event) => values.push(event.cursor),
      onComplete: () => resumed.resolve(),
      onError: () => resumed.resolve()
    });
    cleanup.push(() => resubscription.unsubscribe());
    await resumed.promise;
    expect(values).toEqual(state.events.map((event) => event.cursor));
    expect(state.busyStarts).toBe(2);
    expect(state.mutationStarts).toBe(1);
  });
});
